version: '3.9'

services:
  heron_api:
    build:
      context: .
      dockerfile: Dockerfile.ci
    command: uvicorn heron_app.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    environment:
      BLOCKFROST_PROJECT_ID: preproddummy
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: dummy
      WALLET_ENCRYPTION_KEY: dummy
    depends_on: []