[source]
type = "N2N"
address = ["Tcp", "preprod-node.play.dev.cardano.org:3001"]
magic = 1
min_depth = 10

[source.intersect]
type = "{{ starting_point_type }}"
{% if starting_point_type == "Point" %}
value = [ {{ slot }}, "{{ block_hash }}" ]
{% endif %}

[source.mapper]
include_transaction_details = true

[[filters]]
type = "Selection"

[filters.check]
predicate = "variant_in"
argument = ["Transaction"]

[sink]
type = "Redis"
redis_server = "redis://redis:6379/0"
stream_name = "oura.events"
use_raw = true

[sink.log]
enabled = true

[log]
level = "debug"

[metrics]
address = "0.0.0.0:9186"
endpoint = "/metrics"

[cursor]
type = "File"
path = "/app/oura/cursor"