"""initial schema for minting

Revision ID: 09a1fc0de0b8
Revises: 
Create Date: 2025-06-09 11:31:42.073740

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '09a1fc0de0b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'transaction_mints', 'minting_policies', ['policy_id'], ['policy_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_mints', type_='foreignkey')
    # ### end Alembic commands ###