"""add wallets table

Revision ID: 3a757afbbd32
Revises: e2fcbf8bd85a
Create Date: 2025-05-10 09:58:50.430468

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '3a757afbbd32'
down_revision = 'e2fcbf8bd85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('encrypted_root_key', sa.String(), nullable=False))
    op.drop_column('wallets', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('wallets', 'encrypted_root_key')
    # ### end Alembic commands ###