"""Add minting policies

Revision ID: 3e8132fef3a0
Revises: 7d3fa7a4e9e8
Create Date: 2025-05-22 08:46:05.336138

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '3e8132fef3a0'
down_revision = '7d3fa7a4e9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minting_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('encrypted_policy_skey', sa.String(), nullable=False),
    sa.Column('locking_slot', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('policy_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minting_policies')
    # ### end Alembic commands ###