"""Create wallets table

Revision ID: 495e71c390b8
Revises: 83bf86fc2d4a
Create Date: 2025-05-21 11:26:15.342073

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '495e71c390b8'
down_revision = '83bf86fc2d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###