"""add inline datum to transactions

Revision ID: 4adf86665b64
Revises: 3e8132fef3a0
Create Date: 2025-06-05 18:53:40.164109

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '4adf86665b64'
down_revision = '3e8132fef3a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_outputs', sa.Column('datum', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_outputs', 'datum')
    # ### end Alembic commands ###