"""add tx_hash and error_message to transactions

Revision ID: 734c6cbf94dd
Revises: 3a757afbbd32
Create Date: 2025-05-11 08:00:21.605463

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '734c6cbf94dd'
down_revision = '3a757afbbd32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('tx_hash', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'error_message')
    op.drop_column('transactions', 'tx_hash')
    # ### end Alembic commands ###