"""Add minting policies

Revision ID: 7d3fa7a4e9e8
Revises: 495e71c390b8
Create Date: 2025-05-22 08:41:04.459122

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7d3fa7a4e9e8'
down_revision = '495e71c390b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###