"""add confirmed_at field to transactions

Revision ID: 83bf86fc2d4a
Revises: 55461f202ec7
Create Date: 2025-05-20 14:07:35.947867

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '83bf86fc2d4a'
down_revision = '55461f202ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'confirmed_at')
    # ### end Alembic commands ###