"""add tx_fee and tx_size to transactions

Revision ID: f5c25e0639be
Revises: 734c6cbf94dd
Create Date: 2025-05-11 08:51:08.051807

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f5c25e0639be'
down_revision = '734c6cbf94dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('tx_fee', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('tx_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'tx_size')
    op.drop_column('transactions', 'tx_fee')
    # ### end Alembic commands ###